// This file is auto-generated by scripts/build-shuttle-routes.ts.
// Do not edit this file directly. Update data/shuttle_routes_all.csv instead and
// run `npm run build:shuttle-routes`.

import type { ShuttleRoute } from '../lib/types';

export const shuttleRoutes = [
  {
    "code": "Black",
    "name": "Black Route",
    "color": "#111827",
    "service": {
      "label": "Day Service",
      "days": "Mon-Fri",
      "timeZone": "America/Chicago",
      "start": "07:30",
      "end": "18:00"
    },
    "stops": [
      {
        "id": "lot-50",
        "name": "Lot 50",
        "sequence": 1,
        "lat": 32.724969,
        "lng": -97.111231,
        "address": "1200 S. West St.",
        "isTransferHub": false,
        "transfersTo": [],
        "departurePattern": "window-only"
      },
      {
        "id": "lot-52",
        "name": "Lot 52",
        "sequence": 2,
        "lat": 32.726045,
        "lng": -97.1110301,
        "address": "1101 S. West St.",
        "isTransferHub": false,
        "transfersTo": [],
        "departurePattern": "window-only"
      },
      {
        "id": "lot-53",
        "name": "Lot 53",
        "sequence": 3,
        "lat": 32.7257831,
        "lng": -97.1089414,
        "address": "1100 S. Pecan St",
        "isTransferHub": false,
        "transfersTo": [],
        "departurePattern": "window-only"
      },
      {
        "id": "heights-on-pecan",
        "name": "Heights on Pecan",
        "sequence": 4,
        "lat": 32.7241811,
        "lng": -97.1080681,
        "isTransferHub": false,
        "transfersTo": [],
        "departurePattern": "window-only"
      },
      {
        "id": "college-of-business",
        "name": "College of Business",
        "sequence": 5,
        "lat": 32.7293772,
        "lng": -97.1099721,
        "isTransferHub": true,
        "transfersTo": [
          "Orange"
        ],
        "departurePattern": "window-only"
      }
    ]
  },
  {
    "code": "Blue",
    "name": "Blue Route",
    "color": "#3B82F6",
    "service": {
      "label": "Day Service",
      "days": "Mon-Fri",
      "timeZone": "America/Chicago",
      "start": "07:30",
      "end": "18:00"
    },
    "stops": [
      {
        "id": "mac",
        "name": "MAC",
        "sequence": 1,
        "lat": 32.7318961,
        "lng": -97.1175213,
        "isTransferHub": false,
        "transfersTo": [],
        "departurePattern": "window-only"
      },
      {
        "id": "the-arlie",
        "name": "The Arlie",
        "sequence": 2,
        "lat": 32.7358617,
        "lng": -97.117082,
        "isTransferHub": false,
        "transfersTo": [],
        "departurePattern": "window-only"
      },
      {
        "id": "meadow-run",
        "name": "Meadow Run",
        "sequence": 3,
        "lat": 32.731622,
        "lng": -97.12156,
        "isTransferHub": false,
        "transfersTo": [],
        "departurePattern": "window-only"
      },
      {
        "id": "greek-row",
        "name": "Greek Row",
        "sequence": 4,
        "lat": 32.7308504,
        "lng": -97.1204511,
        "isTransferHub": false,
        "transfersTo": [],
        "departurePattern": "window-only"
      },
      {
        "id": "arbor-oaks",
        "name": "Arbor Oaks",
        "sequence": 5,
        "lat": 32.7309709,
        "lng": -97.1214455,
        "address": "1000 W. Fourth St.",
        "isTransferHub": false,
        "transfersTo": [],
        "departurePattern": "window-only"
      },
      {
        "id": "university-center",
        "name": "University Center",
        "sequence": 6,
        "lat": 32.7321402,
        "lng": -97.1117798,
        "isTransferHub": true,
        "transfersTo": [
          "Black"
        ],
        "departurePattern": "window-only"
      },
      {
        "id": "timber-brook",
        "name": "Timber Brook",
        "sequence": 7,
        "lat": 32.733792,
        "lng": -97.1198758,
        "address": "406 S. Kirby St.",
        "isTransferHub": false,
        "transfersTo": [],
        "departurePattern": "window-only"
      },
      {
        "id": "swift-center",
        "name": "Swift Center",
        "sequence": 8,
        "lat": 32.7341137,
        "lng": -97.1215734,
        "isTransferHub": false,
        "transfersTo": [],
        "departurePattern": "window-only"
      }
    ]
  },
  {
    "code": "Express",
    "name": "Express Route",
    "color": "#10B981",
    "service": {
      "label": "Day Service",
      "days": "Mon-Fri",
      "timeZone": "America/Chicago",
      "start": "07:30",
      "end": "18:00"
    },
    "stops": [
      {
        "id": "p-e-building",
        "name": "P.E. Building",
        "sequence": 1,
        "lat": 32.730745,
        "lng": -97.116562,
        "isTransferHub": false,
        "transfersTo": [],
        "departurePattern": "window-only"
      },
      {
        "id": "mac",
        "name": "MAC",
        "sequence": 2,
        "lat": 32.7318961,
        "lng": -97.1175213,
        "isTransferHub": false,
        "transfersTo": [],
        "departurePattern": "window-only"
      },
      {
        "id": "university-center",
        "name": "University Center",
        "sequence": 3,
        "lat": 32.7321402,
        "lng": -97.1117798,
        "isTransferHub": true,
        "transfersTo": [
          "Black",
          "Blue"
        ],
        "departurePattern": "window-only"
      },
      {
        "id": "arbor-oaks",
        "name": "Arbor Oaks",
        "sequence": 4,
        "lat": 32.7309709,
        "lng": -97.1214455,
        "address": "1000 W. Fourth St.",
        "isTransferHub": false,
        "transfersTo": [],
        "departurePattern": "window-only"
      },
      {
        "id": "lot-27-studio-arts",
        "name": "Lot 27 / Studio Arts",
        "sequence": 5,
        "lat": 32.729227,
        "lng": -97.123753,
        "address": "800 S. Davis St.",
        "isTransferHub": false,
        "transfersTo": [],
        "departurePattern": "window-only"
      },
      {
        "id": "greek-row-lot",
        "name": "Greek Row Lot",
        "sequence": 6,
        "lat": 32.7319794,
        "lng": -97.1217729,
        "address": "600 Summit Ave.",
        "isTransferHub": false,
        "transfersTo": [],
        "departurePattern": "window-only"
      },
      {
        "id": "greek-row",
        "name": "Greek Row",
        "sequence": 7,
        "lat": 32.7308504,
        "lng": -97.1204511,
        "isTransferHub": false,
        "transfersTo": [],
        "departurePattern": "window-only"
      },
      {
        "id": "meadow-run",
        "name": "Meadow Run",
        "sequence": 8,
        "lat": 32.731622,
        "lng": -97.12156,
        "isTransferHub": false,
        "transfersTo": [],
        "departurePattern": "window-only"
      }
    ]
  },
  {
    "code": "Green",
    "name": "Green Route (Shopping)",
    "color": "#22C55E",
    "service": {
      "label": "Green Shopping",
      "days": "Mon-Fri",
      "timeZone": "America/Chicago",
      "start": "18:30",
      "end": "22:30"
    },
    "stops": [
      {
        "id": "university-center",
        "name": "University Center",
        "sequence": 1,
        "lat": 32.7321402,
        "lng": -97.1117798,
        "isTransferHub": true,
        "transfersTo": [],
        "departurePattern": "UC :00/:30",
        "departureTimes": [
          "18:30",
          "19:00",
          "19:30",
          "20:00",
          "20:30",
          "21:00",
          "21:30",
          "22:00",
          "22:30"
        ]
      },
      {
        "id": "walmart",
        "name": "Walmart",
        "sequence": 2,
        "lat": 32.668559,
        "lng": -97.1319118,
        "isTransferHub": false,
        "transfersTo": [],
        "departurePattern": "Walmart :15/:45",
        "departureTimes": [
          "18:45",
          "19:15",
          "19:45",
          "20:15",
          "20:45",
          "21:15",
          "21:45",
          "22:15"
        ],
        "notes": "Confirm exact Walmart store"
      }
    ]
  },
  {
    "code": "Orange",
    "name": "Orange Route",
    "color": "#F97316",
    "service": {
      "label": "Day Service",
      "days": "Mon-Fri",
      "timeZone": "America/Chicago",
      "start": "07:30",
      "end": "18:00"
    },
    "stops": [
      {
        "id": "centennial-court",
        "name": "Centennial Court",
        "sequence": 1,
        "lat": 32.7257832,
        "lng": -97.1163348,
        "isTransferHub": false,
        "transfersTo": [],
        "departurePattern": "window-only"
      },
      {
        "id": "lot-26-stadium",
        "name": "Lot 26 / Stadium",
        "sequence": 2,
        "lat": 32.725997,
        "lng": -97.128006,
        "address": "1301 W. Mitchell St.",
        "isTransferHub": false,
        "transfersTo": [],
        "departurePattern": "window-only"
      },
      {
        "id": "lot-27-studio-arts",
        "name": "Lot 27 / Studio Arts",
        "sequence": 3,
        "lat": 32.729227,
        "lng": -97.123753,
        "address": "800 S. Davis St.",
        "isTransferHub": false,
        "transfersTo": [],
        "departurePattern": "window-only"
      },
      {
        "id": "smart-hospital",
        "name": "Smart Hospital",
        "sequence": 4,
        "lat": 32.7304164,
        "lng": -97.1159214,
        "isTransferHub": false,
        "transfersTo": [],
        "departurePattern": "window-only"
      },
      {
        "id": "college-of-business",
        "name": "College of Business",
        "sequence": 5,
        "lat": 32.7293772,
        "lng": -97.1099721,
        "isTransferHub": true,
        "transfersTo": [
          "Black"
        ],
        "departurePattern": "window-only"
      },
      {
        "id": "848-w-mitchell-st",
        "name": "848 W. Mitchell St.",
        "sequence": 6,
        "lat": 32.7249171,
        "lng": -97.1193965,
        "address": "848 W. Mitchell St.",
        "isTransferHub": false,
        "transfersTo": [],
        "departurePattern": "window-only"
      },
      {
        "id": "maverick-place",
        "name": "Maverick Place",
        "sequence": 7,
        "lat": 32.7243796,
        "lng": -97.119248,
        "isTransferHub": false,
        "transfersTo": [],
        "departurePattern": "window-only"
      },
      {
        "id": "pickard-hall",
        "name": "Pickard Hall",
        "sequence": 8,
        "lat": 32.7287653,
        "lng": -97.1114016,
        "isTransferHub": false,
        "transfersTo": [],
        "departurePattern": "window-only"
      },
      {
        "id": "greek-row",
        "name": "Greek Row",
        "sequence": 9,
        "lat": 32.7308504,
        "lng": -97.1204511,
        "isTransferHub": false,
        "transfersTo": [],
        "departurePattern": "window-only"
      },
      {
        "id": "arbor-oaks",
        "name": "Arbor Oaks",
        "sequence": 10,
        "lat": 32.7309709,
        "lng": -97.1214455,
        "address": "1000 W. Fourth St.",
        "isTransferHub": false,
        "transfersTo": [],
        "departurePattern": "window-only"
      },
      {
        "id": "meadow-run",
        "name": "Meadow Run",
        "sequence": 11,
        "lat": 32.731622,
        "lng": -97.12156,
        "isTransferHub": false,
        "transfersTo": [],
        "departurePattern": "window-only"
      }
    ]
  },
  {
    "code": "Red",
    "name": "Red Route",
    "color": "#EF4444",
    "service": {
      "label": "Red Evening",
      "days": "Mon-Fri",
      "timeZone": "America/Chicago",
      "start": "17:30",
      "end": "21:00"
    },
    "stops": [
      {
        "id": "university-center",
        "name": "University Center",
        "sequence": 1,
        "lat": 32.7321402,
        "lng": -97.1117798,
        "isTransferHub": true,
        "transfersTo": [],
        "departurePattern": "window-only"
      },
      {
        "id": "the-arlie",
        "name": "The Arlie",
        "sequence": 2,
        "lat": 32.7358617,
        "lng": -97.117082,
        "isTransferHub": false,
        "transfersTo": [],
        "departurePattern": "window-only"
      },
      {
        "id": "timber-brook",
        "name": "Timber Brook",
        "sequence": 3,
        "lat": 32.733792,
        "lng": -97.1198758,
        "address": "406 S. Kirby St.",
        "isTransferHub": false,
        "transfersTo": [],
        "departurePattern": "window-only"
      },
      {
        "id": "mac",
        "name": "MAC",
        "sequence": 4,
        "lat": 32.7318961,
        "lng": -97.1175213,
        "isTransferHub": false,
        "transfersTo": [],
        "departurePattern": "window-only"
      },
      {
        "id": "greek-row",
        "name": "Greek Row",
        "sequence": 5,
        "lat": 32.7308504,
        "lng": -97.1204511,
        "isTransferHub": false,
        "transfersTo": [],
        "departurePattern": "window-only"
      },
      {
        "id": "lot-27-studio-arts",
        "name": "Lot 27 / Studio Arts",
        "sequence": 6,
        "lat": 32.729227,
        "lng": -97.123753,
        "address": "800 S. Davis St.",
        "isTransferHub": false,
        "transfersTo": [],
        "departurePattern": "window-only"
      },
      {
        "id": "maverick-stadium",
        "name": "Maverick Stadium",
        "sequence": 7,
        "lat": 32.7292271,
        "lng": -97.1265803,
        "isTransferHub": false,
        "transfersTo": [],
        "departurePattern": "window-only"
      },
      {
        "id": "intramural-fields",
        "name": "Intramural Fields",
        "sequence": 8,
        "lat": 32.7258494,
        "lng": -97.1287734,
        "isTransferHub": false,
        "transfersTo": [],
        "departurePattern": "window-only"
      },
      {
        "id": "maverick-place",
        "name": "Maverick Place",
        "sequence": 9,
        "lat": 32.7243796,
        "lng": -97.119248,
        "isTransferHub": false,
        "transfersTo": [],
        "departurePattern": "window-only"
      },
      {
        "id": "centennial-court",
        "name": "Centennial Court",
        "sequence": 10,
        "lat": 32.7257832,
        "lng": -97.1163348,
        "isTransferHub": false,
        "transfersTo": [],
        "departurePattern": "window-only"
      },
      {
        "id": "lot-53",
        "name": "Lot 53",
        "sequence": 11,
        "lat": 32.7257831,
        "lng": -97.1089414,
        "address": "1100 S. Pecan St",
        "isTransferHub": false,
        "transfersTo": [],
        "departurePattern": "window-only"
      },
      {
        "id": "lot-52",
        "name": "Lot 52",
        "sequence": 12,
        "lat": 32.726045,
        "lng": -97.1110301,
        "address": "1101 S. West St.",
        "isTransferHub": false,
        "transfersTo": [],
        "departurePattern": "window-only"
      },
      {
        "id": "lot-50",
        "name": "Lot 50",
        "sequence": 13,
        "lat": 32.724969,
        "lng": -97.111231,
        "address": "1200 S. West St.",
        "isTransferHub": false,
        "transfersTo": [],
        "departurePattern": "window-only"
      },
      {
        "id": "heights-on-pecan",
        "name": "Heights on Pecan",
        "sequence": 14,
        "lat": 32.7241811,
        "lng": -97.1080681,
        "isTransferHub": false,
        "transfersTo": [],
        "departurePattern": "window-only"
      },
      {
        "id": "college-of-business",
        "name": "College of Business",
        "sequence": 15,
        "lat": 32.7293772,
        "lng": -97.1099721,
        "isTransferHub": true,
        "transfersTo": [],
        "departurePattern": "window-only"
      },
      {
        "id": "college-park-district",
        "name": "College Park District",
        "sequence": 16,
        "lat": 32.7303783,
        "lng": -97.108075,
        "isTransferHub": false,
        "transfersTo": [],
        "departurePattern": "window-only"
      }
    ]
  },
  {
    "code": "Yellow",
    "name": "Yellow Route",
    "color": "#FACC15",
    "service": {
      "label": "Day Service",
      "days": "Mon-Fri",
      "timeZone": "America/Chicago",
      "start": "07:30",
      "end": "18:00"
    },
    "stops": [
      {
        "id": "arlington-hall-cpc",
        "name": "Arlington Hall / CPC",
        "sequence": 1,
        "lat": 32.7278091,
        "lng": -97.1088021,
        "address": "600 S. Spaniolo St.",
        "isTransferHub": true,
        "transfersTo": [
          "Black",
          "Orange"
        ],
        "departurePattern": "window-only"
      },
      {
        "id": "university-center",
        "name": "University Center",
        "sequence": 2,
        "lat": 32.7321402,
        "lng": -97.1117798,
        "isTransferHub": true,
        "transfersTo": [
          "Express",
          "Blue"
        ],
        "departurePattern": "window-only"
      },
      {
        "id": "liv-plus",
        "name": "LIV+",
        "sequence": 3,
        "lat": 32.7273847,
        "lng": -97.1055889,
        "isTransferHub": false,
        "transfersTo": [],
        "departurePattern": "window-only"
      },
      {
        "id": "college-of-business",
        "name": "College of Business",
        "sequence": 4,
        "lat": 32.7293772,
        "lng": -97.1099721,
        "isTransferHub": true,
        "transfersTo": [],
        "departurePattern": "window-only"
      }
    ]
  }
] satisfies ShuttleRoute[];

export default shuttleRoutes;
